### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by antony** [lukeed/trouter#6]
Hi!

So I'm using trouter via Polka -> Sapper, which is great. It's fast!

However I'm trying to diagnose some minor issues and I've noticed there is no logging support. It would be great if there was a slighly more verbose mode for trouter where I could see how routes are being mapped.

Is this something you'd be willing to add / accept a PR on?

**Comment by lukeed** [comment]
Hi, thank you!

No I would not since that is a standard middleware function, which you can easily add thru the Polka interface. 

There are tons of options: pino, bunyan, and morgan just to name a few.

This should probably be raised in Sapper btw, since by default, anything logged (console.log) will be printed to terminal in Polka/Trouter, but not Sapper. Sapper "eats" all terminal output in attempt for a cleaner environment. I don't personally agree with the decision & a few people have had issue with it in the Discord room 

Hope that helps / you see where I'm coming from!
